grpc:
  client:
    pollService:
      address: ${grpc.client.pollService.address}
      negotiationType: PLAINTEXT

firebase:
  webConfigPath: ${firebase.webConfigPath}
  projectId: ${firebase.projectId}
  admin:
    serviceAccountPath: ${firebase.admin.serviceAccountPath}