grpc:
  client:
    pollService:
      address: ${grpc.client.pollService.address}
      negotiationType: PLAINTEXT

firebase:
  webConfigPath: ${firebase.webConfigPath}
  projectId: ${firebase.projectId}
  serviceAccountPath: ${firebase.admin.serviceAccountPath}

spring:
  freemarker:
    suffix: .ftl

server:
  error:
    whitelabel:
      enabled: false